name: indigitall_analytics
version: "1.0.0"
config-version: 2

profile: indigitall

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  default_tenant: "demo"

models:
  indigitall_analytics:
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]
    marts:
      +materialized: table
      +schema: marts
      +tags: ["marts"]
