"""Label Service — Maps technical column names to user-friendly Spanish labels."""

COLUMN_LABELS = {
    # Messages
    "message_count": "Cantidad de Mensajes",
    "count": "Total",
    "total": "Total",
    "direction": "Direccion",
    "contact_name": "Contacto",
    "contact_id": "ID Contacto",
    "agent_id": "Agente",
    "agent_email": "Email Agente",
    "conversation_id": "Conversacion",
    "hour": "Hora del Dia",
    "day_of_week": "Dia de la Semana",
    "date": "Fecha",
    "timestamp": "Fecha/Hora",
    "send_type": "Tipo de Envio",
    "content_type": "Tipo de Contenido",
    "status": "Estado",
    "intent": "Intencion",
    "is_fallback": "Es Fallback",
    "is_bot": "Es Bot",
    "is_human": "Es Humano",
    "message_body": "Mensaje",
    "close_reason": "Razon de Cierre",
    # Contacts
    "total_messages": "Total Mensajes",
    "first_contact": "Primer Contacto",
    "last_contact": "Ultimo Contacto",
    "total_conversations": "Total Conversaciones",
    "unique_contacts": "Contactos Unicos",
    # Agents
    "messages": "Mensajes",
    "conversations": "Conversaciones",
    "conversations_handled": "Conversaciones Atendidas",
    "avg_handle_seconds": "T. Gestion (s)",
    "avg_wait_seconds": "T. Espera (s)",
    "avg_handle_time_seconds": "T. Gestion Prom (s)",
    "wait_time_seconds": "T. Espera (s)",
    "handle_time_seconds": "T. Gestion (s)",
    "active_days": "Dias Activos",
    "active_agents": "Agentes Activos",
    # KPI / Summary
    "Metrica": "Metrica",
    "Valor": "Valor",
    "Porcentaje": "Porcentaje",
    "Estado": "Estado",
    "fallback_rate": "Tasa Fallback",
    "fallback_count": "Mensajes Fallback",
    # Chat Conversations
    "session_id": "ID Sesion",
    "channel": "Canal",
    "queued_at": "En Cola",
    "assigned_at": "Asignado",
    "closed_at": "Cerrado",
    # Toques / Campaigns
    "canal": "Canal",
    "enviados": "Enviados",
    "entregados": "Entregados",
    "clicks": "Clicks",
    "ctr": "CTR (%)",
    "tasa_entrega": "Tasa de Entrega (%)",
    "total_toques": "Total Toques",
    "total_clicks": "Total Clicks",
    # Chat Conversations (extended)
    "first_response_time_seconds": "Tiempo Primera Respuesta (s)",
    "avg_response_time_seconds": "T. Respuesta Prom (s)",
    "dead_time_seconds": "Tiempo Muerto (s)",
    "is_business_hours": "En Horario Laboral",
    "is_resolved_by_bot": "Resuelto por Bot",
    "conversation_type": "Tipo Conversacion",
    "escalated": "Escalado",
    "agent_name": "Nombre Agente",
    "agent_status": "Estado Agente",
    "topic_name": "Tema",
    "channel_name": "Canal",
    "started_at": "Inicio",
    "ended_at": "Fin",
    "duration_seconds": "Duracion (s)",
    "messages_count": "Cant. Mensajes",
    "customer_messages": "Mensajes Cliente",
    "agent_messages": "Mensajes Agente",
    "bot_messages": "Mensajes Bot",
    "wait_time": "Tiempo de Espera",
    "handle_time": "Tiempo de Gestion",
    "first_response_time": "Primera Respuesta",
    # Toques / Campaigns (extended)
    "proyecto": "Proyecto",
    "total_enviados": "Total Enviados",
    "total_entregados": "Total Entregados",
    "total_rechazados": "Total Rechazados",
    "total_pendientes": "Total Pendientes",
    "campana": "Campana",
    "campaign_name": "Nombre Campana",
    "campaign_id": "ID Campana",
    "scheduled_at": "Programado",
    "sent_at": "Enviado",
    "delivered_count": "Entregados",
    "failed_count": "Fallidos",
    "open_count": "Abiertos",
    "click_count": "Clicks",
    "bounce_count": "Rebotados",
    "open_rate": "Tasa Apertura (%)",
    "click_rate": "Tasa Click (%)",
    "bounce_rate": "Tasa Rebote (%)",
    # SMS (extended)
    "telefono": "Telefono",
    "mensaje": "Mensaje",
    "chunks": "Fragmentos",
    "total_chunks": "Total Fragmentos",
    "is_flash": "SMS Flash",
    "status_detail": "Detalle Estado",
    "tipo_envio": "Tipo de Envio",
    "enviado_at": "Fecha Envio",
    "entregado_at": "Fecha Entrega",
    "sms_type": "Tipo SMS",
    # SavedQuery / Dashboard
    "name": "Nombre",
    "description": "Descripcion",
    "query_text": "Texto Consulta",
    "ai_function": "Funcion IA",
    "generated_sql": "SQL Generado",
    "result_row_count": "Filas",
    "result_data": "Datos Resultado",
    "result_columns": "Columnas",
    "visualizations": "Visualizaciones",
    "tags": "Etiquetas",
    "is_favorite": "Favorito",
    "is_archived": "Archivado",
    "is_default": "Por Defecto",
    "created_by": "Creado Por",
    "created_at": "Fecha Creacion",
    "updated_at": "Ultima Actualizacion",
    "updated_by": "Actualizado Por",
    # Contacts (extended)
    "phone": "Telefono",
    "email": "Email",
    "has_conversations": "Tiene Conversaciones",
    "external_id": "ID Externo",
    # Derived
    "category": "Categoria",
    "periodo": "Periodo",
    "tipo_periodo": "Tipo Periodo",
    "entity": "Entidad",
    "tenant_id": "Proyecto",
    "cnt": "Cantidad",
    "id": "ID",
    "type": "Tipo",
    "value": "Valor",
    "rate": "Tasa",
    "percentage": "Porcentaje",
    "avg": "Promedio",
    "min": "Minimo",
    "max": "Maximo",
    "sum": "Suma",
}


def get_label(column_name: str) -> str:
    """Return a user-friendly Spanish label for a column name."""
    return COLUMN_LABELS.get(column_name, column_name.replace("_", " ").title())
